#!/bin/bash

sudo apt-get install -y apt-utils
sudo apt-get install -y dialog
sudo apt update
sudo apt upgrade -y


# Baixa o script
curl -sSL https://raw.githubusercontent.com/astroinova/desktop-tutorial/main/SetupAstro -o SetupAstro

# Verifica se o download foi bem-sucedido
if [ $? -eq 0 ]; then
    # Executa o script baixado
    chmod +x SetupAstro
    ./SetupAstro
else
    echo "Falha ao baixar o script SetupAstro"
fi

sudo apt update
sudo apt upgrade -y

clear
#rm SetupAstro